CREATE USER IF NOT EXISTS API_user IDENTIFIED BY 'password';

CREATE DATABASE IF NOT EXISTS API_dev DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

GRANT ALL PRIVILEGES on API_dev.* to API_user;

CREATE DATABASE IF NOT EXISTS API_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

GRANT ALL PRIVILEGES on API_test.* to API_user;
